# Generated by Django 3.1.1 on 2020-09-29 18:48

from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('real_name', models.CharField(max_length=60)),
                ('tz', timezone_field.fields.TimeZoneField(default='America/Los_Angeles')),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('activity_periods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productapi.member')),
            ],
        ),
    ]
